services:
  postgres:
    image: postgres:16-alpine
    container_name: access-control-postgres
    environment:
      POSTGRES_DB: access_control
      POSTGRES_USER: access_user
      POSTGRES_PASSWORD: access_pass
    ports:
      - "5432:5432"
    volumes:
      - access_control_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U access_user -d access_control"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: access-control-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: access_user
      RABBITMQ_DEFAULT_PASS: access_pass
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: access-control-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  pgadmin:
    image: dpage/pgadmin4:8.13
    container_name: access-control-pgadmin
    profiles:
      - tools
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@empresa.local
      PGADMIN_DEFAULT_PASSWORD: access_pass
    ports:
      - "5050:80"

volumes:
  access_control_postgres_data:
